// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJh3vrMs8m2l6iEP7JbSA1IdfiR27m-bk',
    appId: '1:840433844475:web:73656d5d9ab58b26c5705e',
    messagingSenderId: '840433844475',
    projectId: 'offical-twitter-20231004',
    authDomain: 'offical-twitter-20231004.firebaseapp.com',
    storageBucket: 'offical-twitter-20231004.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rcRdU63HCw5WEGFU9I1I2XVwPn8GAVA',
    appId: '1:840433844475:android:6b9d23f91818bb10c5705e',
    messagingSenderId: '840433844475',
    projectId: 'offical-twitter-20231004',
    storageBucket: 'offical-twitter-20231004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWq2KMnmuLdtVP8hWcaq7lN12sbOD0OA',
    appId: '1:840433844475:ios:023c07b9b2f79b9bc5705e',
    messagingSenderId: '840433844475',
    projectId: 'offical-twitter-20231004',
    storageBucket: 'offical-twitter-20231004.appspot.com',
    iosBundleId: 'com.example.twitterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdWq2KMnmuLdtVP8hWcaq7lN12sbOD0OA',
    appId: '1:840433844475:ios:7e7995cf9f6464d8c5705e',
    messagingSenderId: '840433844475',
    projectId: 'offical-twitter-20231004',
    storageBucket: 'offical-twitter-20231004.appspot.com',
    iosBundleId: 'com.example.twitterDemo.RunnerTests',
  );
}
